metadata:
  name: abacus-web-app

labels:
  testing: "true"

replicaCount: 1

image:
  registry: dwvregistry.azurecr.us
  name: abacus_web_app
  tag: latest
  pullPolicy: Always

env: 
  auth_service: KeycloakAuthService
  upload_service: Hdfs
  hdfs:
    enabled: True
    profile: dev
    config: /configs/hdfs_config.conf

config:
  name: abacus-web-app-config
  keycloak:
    base_url: https://keycloak-eval.opalacceptance.dso.mil
    realm: datawave
    client_id: external-client
    client_secret: jxNx0kaiSyfs6xSviHH4tXInn0pdswsN
  hdfs:
    client: InsecureClient
    url: http://hdfs-nn.datawave.svc.cluster.local:9870
    user: datawave
