metadata:
  name: abacus-web-app

labels:
  testing: "true"

replicaCount: 1

image:
  registry: dwvregistry.azurecr.us
  name: abacus_web_app
  tag: latest
  pullPolicy: Always

env: 
  auth_service: KeycloakAuthService
  upload_service: Mock

config:
  name: abacus-web-app-config
  keycloak:
    base_url: https://keycloak-eval.opalacceptance.dso.mil
    realm: datawave
    client_id: external-client
    client_secret: jxNx0kaiSyfs6xSviHH4tXInn0pdswsN
