apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.keycloak_config.name }}
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{ end }}
data:
  keycloak_config.json: |
    {
    "web": {
        "issuer": "http://localhost:8080/realms/{{ .Values.keycloak_config.realm }}",
        "auth_uri": "http://localhost:8080/realms/{{ .Values.keycloak_config.realm }}/protocol/openid-connect/auth",
        "client_id": "{{ .Values.keycloak_config.client_id }}",
        "client_secret": "{{ .Values.keycloak_config.client_secret }}",
        "redirect_uris": [
            "http://localhost:5000/*"
        ],
        "userinfo_uri": "http://localhost:8080/realms/{{ .Values.keycloak_config.realm }}/protocol/openid-connect/userinfo",
        "token_uri": "http://localhost:8080/realms/{{ .Values.keycloak_config.realm }}/protocol/openid-connect/token",
        "token_introspection_uri": "http://localhost:8080/realms/{{ .Values.keycloak_config.realm }}/protocol/openid-connect/token/introspect"
        }
    }