apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{ end }}
data:
  keycloak_config.json: |
    {
    "web": {
        "issuer": "{{ .Values.config.keycloak.base_url }}/realms/{{ .Values.config.keycloak.realm }}",
        "auth_uri": "{{ .Values.config.keycloak.base_url }}/realms/{{ .Values.config.keycloak.realm }}/protocol/openid-connect/auth",
        "client_id": "{{ .Values.config.keycloak.client_id }}",
        "client_secret": "{{ .Values.config.keycloak.client_secret }}",
        "redirect_uris": [
            "http://localhost:5000/*"
        ],
        "userinfo_uri": "{{ .Values.config.keycloak.base_url }}/realms/{{ .Values.config.keycloak.realm }}/protocol/openid-connect/userinfo",
        "token_uri": "{{ .Values.config.keycloak.base_url }}/realms/{{ .Values.config.keycloak.realm }}/protocol/openid-connect/token",
        "token_introspection_uri": "{{ .Values.config.keycloak.base_url }}/realms/{{ .Values.config.keycloak.realm }}/protocol/openid-connect/token/introspect",
        "client_kwargs": {
          "verify": "False"
        }
        }
    }
  
  {{ if .Values.env.hdfs.enabled }}
  hdfs_config.conf: |
    [global]
    default.alias = {{ .Values.env.hdfs.profile }}

    [{{ .Values.env.hdfs.profile }}.alias]
    client = {{ .Values.config.hdfs.client }}
    url = {{ .Values.config.hdfs.url }}
    user = {{ .Values.config.hdfs.user }}
  {{ end }}